name: Tests

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    tests:

        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php-versions: [ '7.4' ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP, extensions and composer with shivammathur/setup-php
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo
                    tools: php-cs-fixer, phpunit, phpcs
                env:
                    update: true

            -   name: Validate composer.json and composer.lock
                run: composer validate

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-

            -   name: Install dependencies
                if: steps.composer-cache.outputs.cache-hit != 'true'
                run: make install

            -   name: Check the Symfony console
                run: php bin/console -V

            -   name: Run unit tests
                run: make test

            -   name: Run CS
                run: |
                    make cs
                    make cs-check
